### ISSUE TITLE
Request has been deprecated

### ISSUE THREAD

**Issue by ffffnk** [naddison36/sol2uml#11]
Sol2uml throws an error since request has been deprecated (https://github.com/request/request/issues/3142).

i.e.

>sol2uml ./contracts
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'request'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (C:\U...\npm\node_modules\sol2uml\lib\etherscanParser.js:6:35)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)

**Comment by naddison36** [comment]
Thanks for raising this. The new version 1.1.13 replaces `request` with `axios`
