### ISSUE TITLE
Error: Cannot find module '@solidity-parser/parser'

### ISSUE THREAD

**Issue by SudeshGagare** [naddison36/sol2uml#19]
cosmos@ubuntu:~$ sol2uml -h
internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module '@solidity-parser/parser'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/sol2uml/lib/etherscanParser.js:7:18)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)

**Comment by naddison36** [comment]
Is this a new install or an update to an existing installation?
sol2uml recently switched to the https://github.com/solidity-parser/parser parser. The above error is the new parser has not been installed.
You can find where sol2uml is installed, eg ``ls -l `which sol2uml` ``, and then run `npm install`

**Comment by SudeshGagare** [comment]
Thanks a lot!!!
Resolved the issue.
